server:
  port: 8090

spring:
  application:
    name: tagcollector
  datasource:
    url: jdbc:h2:file:./src/main/resources/db/data/rcdb.mv.db
    username: den
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect